env_files = []
root = "."
testdata_dir = "testdata"
tmp_dir = "bin"

[build]
  bin = "./bin/debug/moniserve"
  cmd = "make build-debug"
  delay = 500
  entrypoint = ["./bin/debug/moniserve"]

[screen]
  clear_on_rebuild = true
  keep_scroll = true
